name: Stale Branches

on: workflow_dispatch

jobs:
  stale-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: abhishekdiwan1227/common-actions/stale-branches@master
        id: stale-branch
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo branches=${{ steps.stale-branch.outputs.branches-list }} >> $GITHUB_STEP_SUMMARY
